### ISSUE TITLE
PDF Quality

### ISSUE THREAD

**Issue by efpob** [mtolly/jammittools#6]
Is there anyway to increase the DPI/quality of the generated PDF files?

Thanks!!

**Comment by mtolly** [comment]
Hey efpob. I don't think there is; the PDFs are generated from simple PNGs in the Jammit data folders, which are of a fixed, not-too-high resolution of 1024 pixels wide. Here's an example (click to see the exact size):

![44ad9a6a-1b6a-4a2e-a698-a0495870112e_jcfn_12](https://cloud.githubusercontent.com/assets/1427698/18756581/15b1880a-80b6-11e6-9746-1a4af7d57960.png)

If the PDFs you're getting are less than that do let me know! Otherwise sadly that's what Jammit provides.

**Comment by efpob** [comment]
I was afraid of that; the image above matches the PDF quality - thanks for the explanation
