### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by carlosmiguelco** [mtolly/jammittools#7]
Firstly, thank you very much for helping us!
I have a noob issue on MacOS Sierra. When I run the script causes this error:
"jammittools: Dream Theater - Through My Words_Fatal Tragedy: createDirectory: permission denied (Permission denied)"

Thanks!

**Comment by mtolly** [comment]
Hi Carlos! Sorry for the delay in responding.

Hmm... I have not yet upgraded my Mac to Sierra but I had one other user with a similar problem so I suspect there has been some change made to permissions policy by Apple that is causing the issue. Can you try the following in order to run it from the command line directly:

1. move the `jammittools` executable (the file simply named `jammittools`) to the Desktop

2. open Terminal.app and run each of the following commands:

```
cd Desktop
mkdir export
./jammittools -b export
```

Let me know if that gives the same result, or if the instructions are unclear.

**Comment by carlosmiguelco** [comment]
Hi, mtolly!
Now it worked perfectly! 
Thank you so much again!
